"""Galvo plant model used for early control-loop simulation.

The model combines:
1) Electrical coil dynamics: V = R*i + L*di/dt + Kt*omega
2) Mechanical rotor dynamics: Kt*i = J*domega/dt + B*omega

The state is integrated with explicit Euler at the PWM-rate timestep.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict


# G120 (small, fast)
G120_PARAMS: Dict[str, float] = {
    "R": 3.0,  # Ω coil resistance
    "L": 0.5e-3,  # H coil inductance
    "Kt": 0.01,  # Nm/A torque constant
    "J": 0.05e-7,  # kg·m² rotor + mirror inertia
    "B": 1e-6,  # Nm·s/rad viscous damping
}

# CT-6800 (large, powerful)
CT6800_PARAMS: Dict[str, float] = {
    "R": 1.5,  # Ω coil resistance
    "L": 1.5e-3,  # H coil inductance
    "Kt": 0.02,  # Nm/A torque constant
    "J": 2.0e-7,  # kg·m² rotor + mirror inertia
    "B": 5e-6,  # Nm·s/rad viscous damping
}


@dataclass
class GalvoPlant:
    """Single-axis galvo plant.

    Attributes:
        R, L, Kt, J, B: Electrical/mechanical model parameters.
        i: Coil current [A].
        omega: Mirror angular speed [rad/s].
        theta: Mirror angle [rad].
    """

    R: float
    L: float
    Kt: float
    J: float
    B: float
    i: float = 0.0
    omega: float = 0.0
    theta: float = 0.0

    @classmethod
    def from_params(cls, params: Dict[str, float]) -> "GalvoPlant":
        """Build a plant from a parameter dictionary."""
        return cls(**params)

    def reset(self) -> None:
        """Reset plant state to rest."""
        self.i = 0.0
        self.omega = 0.0
        self.theta = 0.0

    def step(self, voltage: float, dt: float) -> None:
        """Advance the plant by one timestep using Euler integration.

        Args:
            voltage: Coil drive voltage command [V].
            dt: Timestep [s], typically the PWM period.
        """
        # Electrical subsystem: current evolves from applied voltage minus
        # resistive drop and back-EMF generated by rotor motion.
        di_dt = (voltage - self.R * self.i - self.Kt * self.omega) / self.L
        self.i += di_dt * dt

        # Mechanical subsystem: electromagnetic torque accelerates inertia
        # against viscous damping.
        domega_dt = (self.Kt * self.i - self.B * self.omega) / self.J
        self.omega += domega_dt * dt
        self.theta += self.omega * dt

